/*
 * @file sbom_tools.h
 * @brief C ABI for sbom-tools — SBOM parsing, diffing, and quality scoring.
 *
 * GENERATED by cbindgen from src/ffi.rs — DO NOT EDIT BY HAND.
 * Regenerate via `cbindgen --config crates/sbom-tools-ffi/cbindgen.toml`.
 *
 * Every SbomToolsStringResult MUST be freed exactly once via
 * sbom_tools_string_result_free(). Reuse after free is undefined behavior.
 */

#ifndef SBOM_TOOLS_H
#define SBOM_TOOLS_H

#include <stdint.h>

/**
 * Stable error codes for the C ABI.
 */
enum SbomToolsErrorCode
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * Successful operation.
   */
  SBOM_TOOLS_ERROR_CODE_OK = 0,
  /**
   * Parsing of raw SBOM input failed.
   */
  SBOM_TOOLS_ERROR_CODE_PARSE = 1,
  /**
   * Semantic diffing failed.
   */
  SBOM_TOOLS_ERROR_CODE_DIFF = 2,
  /**
   * Validation of normalized JSON input failed.
   */
  SBOM_TOOLS_ERROR_CODE_VALIDATION = 3,
  /**
   * IO failed while reading from disk.
   */
  SBOM_TOOLS_ERROR_CODE_IO = 4,
  /**
   * Requested functionality is unsupported.
   */
  SBOM_TOOLS_ERROR_CODE_UNSUPPORTED = 5,
  /**
   * Unexpected internal failure.
   */
  SBOM_TOOLS_ERROR_CODE_INTERNAL = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SbomToolsErrorCode SbomToolsErrorCode;
#else
typedef uint32_t SbomToolsErrorCode;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Stable scoring profile identifiers for the C ABI.
 */
enum SbomToolsScoringProfile
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  SBOM_TOOLS_SCORING_PROFILE_MINIMAL = 0,
  SBOM_TOOLS_SCORING_PROFILE_STANDARD = 1,
  SBOM_TOOLS_SCORING_PROFILE_SECURITY = 2,
  SBOM_TOOLS_SCORING_PROFILE_LICENSE_COMPLIANCE = 3,
  SBOM_TOOLS_SCORING_PROFILE_CRA = 4,
  SBOM_TOOLS_SCORING_PROFILE_COMPREHENSIVE = 5,
  SBOM_TOOLS_SCORING_PROFILE_AI_READINESS = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum SbomToolsScoringProfile SbomToolsScoringProfile;
#else
typedef uint32_t SbomToolsScoringProfile;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Generic string payload result for the C ABI.
 */
typedef struct {
  /**
   * JSON payload on success.
   */
  char *data;
  /**
   * Stable ABI error code.
   */
  SbomToolsErrorCode error_code;
  /**
   * UTF-8 error message on failure.
   */
  char *error_message;
} SbomToolsStringResult;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the ABI and crate versions as JSON.
 */
SbomToolsStringResult sbom_tools_abi_version_json(void);

/**
 * Detect the SBOM format from raw content and return JSON.
 */
SbomToolsStringResult sbom_tools_detect_format_json(const char *content);

/**
 * Parse an SBOM file from disk and return normalized JSON.
 */
SbomToolsStringResult sbom_tools_parse_sbom_path_json(const char *path);

/**
 * Parse raw SBOM content and return normalized JSON.
 */
SbomToolsStringResult sbom_tools_parse_sbom_str_json(const char *content);

/**
 * Diff two normalized SBOM JSON documents and return a diff result as JSON.
 */
SbomToolsStringResult sbom_tools_diff_sboms_json(const char *old_sbom_json,
                                                 const char *new_sbom_json);

/**
 * Score a normalized SBOM JSON document and return a quality report as JSON.
 */
SbomToolsStringResult sbom_tools_score_sbom_json(const char *sbom_json,
                                                 SbomToolsScoringProfile profile);

/**
 * Free memory allocated by the ABI result.
 *
 * # Safety
 * - The caller must call this exactly once per result.
 * - The result must not be used after this call.
 * - Calling free twice on the same result is **undefined behavior**: the struct
 *   is passed by value (C calling convention), so the caller's copy retains
 *   the original (now-dangling) pointers. The internal pointer zeroing only
 *   affects the local copy inside this function.
 *
 * # C Usage
 * ```c
 * SbomToolsStringResult result = sbom_tools_parse_sbom_str_json(content);
 * // use result.data and result.error_message
 * sbom_tools_string_result_free(result);
 * // Do NOT call sbom_tools_string_result_free(result) again — undefined behavior.
 * ```
 */
void sbom_tools_string_result_free(SbomToolsStringResult result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SBOM_TOOLS_H */
